name: Run Jest tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  jestTest:
    runs-on: macos-latest 
    env:
          MONGO_DB: ${{ secrets.MONGO_DB }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: cd Server && npm i
      - run: npm test -- --testPathPattern=Server/tests/
